FROM python:3.11-slim

WORKDIR /app

# Install system dependencies (minimal)
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

EXPOSE 8000

# Set environment variable for database URL
ENV DATABASE_URL=sqlite:////app/data/metrics.db


# Create a directory for storing data
RUN mkdir -p /app/data


CMD ["uvicorn", "ingest.app:app", "--host", "0.0.0.0", "--port", "8000"]
